export const assets = [
  {
    name: "Vercel deploy button",
    code: `[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://github.com/[user-name]/[repo-name])`,
    keywords: [
      "vercel",
      "deploy",
      "button",
      "deploy button",
      "vercel deploy button",
      "vercel button",
      "vercel deploy",
    ],
  },
  {
    name: "Heroku deploy button",
    code: `[![Deploy with heroku](https://www.herokucdn.com/deploy/button.svg)](https://www.heroku.com/deploy/?template=[template-url])]`,
    keywords: [
      "heroku",
      "deploy",
      "button",
      "deploy button",
      "heroku deploy button",
      "heroku button",
      "heroku deploy",
    ],
  },
  {
    name: "Netlify deploy button",
    code: `[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=[repo-url])]`,
    keywords: [
      "netlify",
      "deploy",
      "button",
      "deploy button",
      "netlify deploy button",
      "netlify button",
      "netlify deploy",
    ],
  },
  {
    name: "Cloudflare workers deploy button",
    code: `[![Deploy to Cloudflare Workers](https://deploy.workers.cloudflare.com/button)](https://deploy.workers.cloudflare.com/?url=https://github.com/[user-name]/[repo-name])`,
    keywords: [
      "cloudflare",
      "deploy",
      "button",
      "deploy button",
      "cloudflare deploy button",
      "cloudflare button",
      "cloudflare deploy",
    ],
  },
  {
    name: "CodeSandbox edit button",
    code: `[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/[sandbox-id])`,
    keywords: [
      "codesandbox",
      "deploy",
      "button",
      "deploy button",
      "codesandbox edit button",
      "codesandbox button",
      "codesandbox edit",
    ],
  },
  {
    name: "Made with repl.it button",
    code: `[![Made with Repl.it](https://repl.it/badge/github/[user-name]/[repo-name])]([repl-url])`,
    keywords: [
      "repl.it",
      "run",
      "button",
      "run button",
      "repl.it run button",
      "repl.it button",
      "repl.it run",
    ],
  },
  {
    name: "Run on replit button",
    code: `[![Run on Replit](https://binbashbanana.github.io/deploy-buttons/buttons/official/replit.svg)](https://replit.com/github/[user-name]/[repo-name])`,
    keywords: [
      "replit",
      "run",
      "button",
      "run button",
      "replit run button",
      "replit button",
      "replit run",
    ],
  },
  {
    name: "Remix on Glitch button",
    code: `[![Remix on Glitch](https://binbashbanana.github.io/deploy-buttons/buttons/official/glitch.svg)](https://glitch.com/edit/#!/import/github/[user-name]/[repo-name])`,
    keywords: [
      "glitch",
      "remix",
      "button",
      "remix button",
      "glitch remix button",
      "glitch button",
      "glitch remix",
    ],
  },
  {
    name: "Deploy to Azure button",
    code: `[![Deploy to Azure](https://binbashbanana.github.io/deploy-buttons/buttons/official/azure.svg)](https://portal.azure.com/#create/Microsoft.Template/uri/[template-uri])`,
    keywords: [
      "azure",
      "deploy",
      "button",
      "deploy button",
      "azure deploy button",
      "azure button",
      "azure deploy",
    ],
  },
  {
    name: "Deploy to IBM Cloud button",
    code: `[![Deploy to IBM Cloud](https://binbashbanana.github.io/deploy-buttons/buttons/official/ibmcloud.svg)](https://cloud.ibm.com/devops/setup/deploy?repository=https://github.com/[user-name]/[repo-name])`,
    keywords: [
      "ibm",
      "ibm cloud",
      "deploy",
      "button",
      "deploy button",
      "ibm cloud deploy button",
      "ibm cloud button",
      "ibm cloud deploy",
    ],
  },
  {
    name: "Deploy to Amplify Console button",
    code: `[![Deploy to Amplify Console](https://binbashbanana.github.io/deploy-buttons/buttons/official/amplifyconsole.svg)](https://console.aws.amazon.com/amplify/home#/deploy?repo=https://github.com/[user-name]/[repo-name])`,
    keywords: [
      "amplify",
      "amplify console",
      "deploy",
      "button",
      "deploy button",
      "amplify console deploy button",
      "amplify console button",
      "amplify console deploy",
    ],
  },
  {
    name: "Run on Google Cloud button",
    code: `[![Run on Google Cloud](https://binbashbanana.github.io/deploy-buttons/buttons/official/googlecloud.svg)](https://deploy.cloud.run/?git_repo=https://github.com/[user-name]/[repo-name])`,
    keywords: [
      "google",
      "google cloud",
      "deploy",
      "button",
      "deploy button",
      "google cloud deploy button",
      "google cloud button",
      "google cloud deploy",
    ],
  },
  {
    name: "Deploy to Oracle Cloud button",
    code: `[![Deploy to Oracle Cloud](https://binbashbanana.github.io/deploy-buttons/buttons/official/oraclecloud.svg)](https://cloud.oracle.com/resourcemanager/stacks/create?zipUrl=[zip-url])`,
    keywords: [
      "oracle",
      "oracle cloud",
      "deploy",
      "button",
      "deploy button",
      "oracle cloud deploy button",
      "oracle cloud button",
      "oracle cloud deploy",
    ],
  },
  {
    name: "Deploy on railway button",
    code: `[![Deploy on Railway](https://binbashbanana.github.io/deploy-buttons/buttons/official/railway.svg)](https://railway.app/new/template?template=https://github.com/[user-name]/[repo-name])`,
    keywords: [
      "railway",
      "deploy",
      "button",
      "deploy button",
      "railway deploy button",
      "railway button",
      "railway deploy",
    ],
  },
  {
    name: "Deploy to koyeb button",
    code: `[![Deploy to Koyeb](https://binbashbanana.github.io/deploy-buttons/buttons/official/koyeb.svg)](https://app.koyeb.com/deploy?type=git&repository=github.com/[user-name]/[repo-name]&branch=[branch]&name=[name])`,
    keywords: [
      "koyeb",
      "deploy",
      "button",
      "deploy button",
      "koyeb deploy button",
      "koyeb button",
      "koyeb deploy",
    ],
  },
  {
    name: "Deploy to Render button",
    code: `[![Deploy to Render](https://binbashbanana.github.io/deploy-buttons/buttons/official/render.svg)](https://render.com/deploy?repo=https://github.com/[user-name]/[repo-name])`,
    keywords: [
      "render",
      "deploy",
      "button",
      "deploy button",
      "render deploy button",
      "render button",
      "render deploy",
    ],
  },
  {
    name: "Deploy to cyclic button",
    code: `[![Deploy to Cyclic](https://binbashbanana.github.io/deploy-buttons/buttons/official/cyclic.svg)](https://app.cyclic.sh/api/app/deploy/[user-name]/[repo-name])`,
    keywords: [
      "cyclic",
      "deploy",
      "button",
      "deploy button",
      "cyclic deploy button",
      "cyclic button",
      "cyclic deploy",
    ],
  },

  {
    code: `![Made with love](https://forthebadge.com/images/badges/built-with-love.svg)`,
    name: "Made with love",
  },
  {
    code: `![Made with python](https://forthebadge.com/images/badges/made-with-python.svg)`,
    name: "Made with python",
  },
  {
    code: `![Made with javascript](https://forthebadge.com/images/badges/made-with-javascript.svg)`,
    name: "Made with javascript",
  },
  {
    code: `![Made with ruby](https://forthebadge.com/images/badges/made-with-ruby.svg)`,
    name: "Made with ruby",
  },
  {
    code: `![Made with java](https://forthebadge.com/images/badges/made-with-java.svg)`,
    name: "Made with java",
  },
  {
    code: `![Made with c++](https://forthebadge.com/images/badges/made-with-c-plus-plus.svg)`,
    name: "Made with c++",
  },
  {
    code: `![Made with c#](https://forthebadge.com/images/badges/made-with-c-sharp.svg)`,
    name: "Made with c#",
  },
  {
    code: `![Made with typescript](https://forthebadge.com/images/badges/made-with-typescript.svg)`,
    name: "Made with typescript",
  },
  {
    code: `![Made with swift](https://forthebadge.com/images/badges/made-with-swift.svg)`,
    name: "Made with swift",
  },
  {
    code: `![Made with rust](https://forthebadge.com/images/badges/made-with-rust.svg)`,
    name: "Made with rust",
  },
  {
    code: "![Works on my machine](https://forthebadge.com/images/badges/works-on-my-machine.svg)",
    name: "Works on my machine",
  },
  {
    code: "Built by developers![Built by developers](https://forthebadge.com/images/badges/built-by-developers.svg)",
    name: "Built by developers",
  },
  {
    code: "![Built with science](https://forthebadge.com/images/badges/built-with-science.svg)",
    name: "Built with science",
  },
  {
    code: "![Made with javascript](https://forthebadge.com/images/badges/made-with-javascript.svg)",
    name: "Made with javascript",
  },
  {
    code: "![Made with reason](https://forthebadge.com/images/badges/made-with-reason.svg)",
    name: "Made with reason",
  },
  {
    code: "![Made with sphinx](https://img.shields.io/badge/Made%20with-Sphinx-1f425f.svg)",
    name: "Made with sphinx",
  },
  {
    code: "![Made with jupiter](https://img.shields.io/badge/Made%20with-Jupyter-orange?style=for-the-badge&logo=Jupyter)",
    name: "Made with jupiter",
  },
  {
    code: "![Made with markdown](https://img.shields.io/badge/Made%20with-Markdown-1f425f.svg)",
    name: "Made with markdown",
  },
  {
    code: "![Made with latex](https://img.shields.io/badge/Made%20with-LaTeX-1f425f.svg)",
    name: "Made with latex",
  },
  {
    code: "![Made with mathjax](https://img.shields.io/badge/Made%20with-MathJax-1f425f.svg)",
    name: "Made with mathjax",
  },
  {
    code: "![Made with bash](https://img.shields.io/badge/Made%20with-Bash-1f425f.svg)",
    name: "Made with bash",
  },
  {
    code: "![Made for VSCode](https://img.shields.io/badge/Made%20for-VSCode-1f425f.svg)",
    name: "Made for VSCode",
  },

  {
    name: "Static badge",
    code: `![Static badge](https://img.shields.io/static/v1?label=[label]&message=[message]&color=[color]&style=[style]&logo=[named-logo]&logoColor=[logo-color])`,
    keywords: [
      "static",
      "badge",
      "static badge",
      "static badge",
      "static badge",
      "static badge",
    ],
  },
  {
    name: "GitHub stars",
    code: `![GitHub Repo stars](https://img.shields.io/github/stars/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "stars",
      "badge",
      "github stars",
      "github badge",
      "github stars badge",
    ],
  },
  {
    name: "GitHub forks",
    code: `![GitHub Repo forks](https://img.shields.io/github/forks/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "forks",
      "badge",
      "github forks",
      "github badge",
      "github forks badge",
    ],
  },
  {
    name: "GitHub watchers",
    code: `![GitHub Repo watchers](https://img.shields.io/github/watchers/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])
        `,
    keywords: [
      "github",
      "watchers",
      "badge",
      "github watchers",
      "github badge",
      "github watchers badge",
    ],
  },
  {
    name: "GitHub issues open",
    code: `![GitHub issues](https://img.shields.io/github/issues/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "issues",
      "badge",
      "github issues",
      "github badge",
      "github issues badge",
    ],
  },
  {
    name: "GitHub pull requests",
    code: `![GitHub pull requests](https://img.shields.io/github/issues-pr/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "pull requests",
      "badge",
      "github pull requests",
      "github badge",
      "github pull requests badge",
    ],
  },
  {
    name: "Github contributors",
    code: `![GitHub contributors](https://img.shields.io/github/contributors/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "contributors",
      "badge",
      "github contributors",
      "github badge",
      "github contributors badge",
    ],
  },
  {
    name: "GitHub last commit",
    code: `![GitHub last commit](https://img.shields.io/github/last-commit/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "last commit",
      "badge",
      "github last commit",
      "github badge",
      "github last commit badge",
    ],
  },
  {
    name: "GitHub commit activity",
    code: `![GitHub commit activity](https://img.shields.io/github/commit-activity/m/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "commit activity",
      "badge",
      "github commit activity",
      "github badge",
      "github commit activity badge",
    ],
  },
  {
    name: "Licence badge",
    code: `![Licence badge](https://img.shields.io/github/license/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "licence",
      "badge",
      "licence badge",
      "licence badge",
      "licence badge",
      "licence badge",
    ],
  },
  {
    name: "GitHub release badge",
    code: `![GitHub release badge](https://img.shields.io/github/v/release/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "release",
      "badge",
      "github release",
      "github badge",
      "github release badge",
    ],
  },
  {
    name: "Github commits since",
    code: `![Github commits since](https://img.shields.io/github/commits-since/[user-name]/[repo-name]/[version]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "commits since",
      "badge",
      "github commits since",
      "github badge",
      "github commits since badge",
    ],
  },
  {
    name: "Github downloads",
    code: `![Github downloads](https://img.shields.io/github/downloads/[user-name]/[repo-name]/total?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "downloads",
      "badge",
      "github downloads",
      "github badge",
      "github downloads badge",
    ],
  },
  {
    name: "Github followers",
    code: `![Github followers](https://img.shields.io/github/followers/[user-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "followers",
      "badge",
      "github followers",
      "github badge",
      "github followers badge",
    ],
  },
  {
    name: "Github issues closed",
    code: `![Github issues closed](https://img.shields.io/github/issues-closed/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "issues closed",
      "badge",
      "github issues closed",
      "github badge",
      "github issues closed badge",
    ],
  },
  {
    name: "Github pull requests closed",
    code: `![Github pull requests closed](https://img.shields.io/github/issues-pr-closed/[user-name]/[repo-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: [
      "github",
      "pull requests closed",
      "badge",
      "github pull requests closed",
      "github badge",
      "github pull requests closed badge",
    ],
  },
  {
    name: "Npm version",
    code: `![Npm Version](https://img.shields.io/npm/v/[package-name]?color=[override-color]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style])`,
    keywords: ["npm", "npm version", "version", "Npm version badge"],
  },
  {
    name: "Website status",
    code: `![Website status](https://img.shields.io/website?color=[override-color]&down_color=[down-color]&down_message=[down-message]&label=[override-label]&logo=[named-logo]&logoColor=[logo-color]&style=[style]&up_color=[up-color]&up_message=[up-message]&url=[url])`,
    keywords: [
      "website",
      "status",
      "badge",
      "website status",
      "badge",
      "website status badge",
    ],
  },
]
